repos:
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.4
    hooks:
    -   id: reorder-python-imports
        files: '(\.py|wscript)$'
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: check-yaml
        name: check-yaml - Validating .yaml Files
        exclude: \{\{cookiecutter.project_slug\}\}/(readthedocs|environment|.travis).yml
-   repo: local
    hooks:
    - id: black
      name: Black - The Uncompromising Code Formatter
      language: system
      entry: black
      files: '(\.pyi?|wscript)$'
    - id: flake8
      name: flake8
      language: system
      entry: flake8 - Linting
      types: [python]
      additional_dependencies: [flake8-alfred]
